# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./ml-services:/app/ml-services
    env_file:
      - ./.env
    # --- ADD THIS SECTION ---
    environment:
      - PYTHONPATH=/app
    # ------------------------
    depends_on:
      db:
        condition: service_healthy

  # ... (the rest of your db service is unchanged) ...
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: